language: c++
compiler: gcc
sudo: require
dist: trusty

addons:
  apt:
    packages:
      - clang-3.8
      - cmake
      - g++-4.8

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update

install:
  - sudo apt-get -y install qt55base
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - cmake -DCMAKE_BUILD_TYPE= -G "CodeBlocks - Unix Makefiles" --target Bitwolf_Engine .

before_script:
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh
