language: c++
compiler: gcc
sudo: require
dist: trusty

addons:
  apt:
    packages:
      - clang-3.8
      - cmake
      - g++-4.8

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt594-trusty
  - sudo apt-get -qq update

install:
  - cat /opt/qt59/bin/qt59-env.sh
  - /opt/qt59/bin/qt59-env.sh
  - sudo apt-get -y install qt510base
  - ls -al /opt/
  - ls -al /opt/qt59
  - ls -al /opt/qt59/lib
  - export CMAKE_PREFIX_PATH="/opt/qt59/lib/cmake/"
  - env
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

script: cmake -DCMAKE_BUILD_TYPE= -G "CodeBlocks - Unix Makefiles" --target Bitwolf_Engine .
