language: c++
compiler: gcc
sudo: require
dist: xenial

addons:
  apt:
    packages:
      - clang-3.8
      - cmake
      - g++-4.8

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.10.0-xenial
  - sudo apt-get -qq update

install:
  - sudo apt-get -y install qt510base
  - ls -al /opt/
  - ls -al /opt/qt510
  - ls -al /opt/qt510/lib
  - export CMAKE_PREFIX_PATH="/opt/qt510/lib/cmake/"
  - env
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

script: cmake -DCMAKE_BUILD_TYPE= -G "CodeBlocks - Unix Makefiles" --target Bitwolf_Engine .
