language: c++
compiler: gcc
sudo: require
dist: trusty

addons:
  apt:
    packages:
      - clang-5
      - cmake
      - g++-4.8

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt594-trusty
  - sudo apt-get -qq update

install:
  - sudo apt-get -y install qt59base
  - /opt/qt59/bin/qt59-env.sh
  - export CMAKE_PREFIX_PATH="/opt/qt59/lib/cmake/"

script: cmake -DCMAKE_BUILD_TYPE= -G "CodeBlocks - Unix Makefiles" --target Bitwolf_Engine .
